name: Run MySide tests
on:
  push:
    branches: "**"
  pull_request:
    branches:
      - main
jobs:
  NextJS-Tests:
    name: Run MySide tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
        env:
          NEXT_PUBLIC_API_URL: https://fakestoreapi.in/api